### ISSUE TITLE
PhpUnit is not running

### ISSUE THREAD

**Issue by gmponos** [markstory/cakephp-spekkoek#6]
What I did.
- Cloned the project
- Run `composer update`
- Run `phpunit` on master branch with no change
  Then I got an error saying 

> PHP Fatal error:  Class 'Cake\Core\Configure' not found in /var/www/html/CakePHP/cakephp-spekkoek/tests/bootstrap.php on line 32
> PHP Stack trace:

It seems that vendor/autoload.php is not bootstrapped in the xml file of PhpUnit.

**Comment by markstory** [comment]
Thanks! Should be good now. I'm not sure why travis-ci and my local install worked but yours did not.
